// Re-export the generated protobuf-es types the clients need. The WebSocket wire
// contract is binary protobuf (whatsapp.ws.v1); the transport encodes/decodes
// with FrameSchema via @bufbuild/protobuf. Generated by protoc-gen-es into
// ./gen (buf.gen.yaml); nothing here is hand-written except this barrel.
export * from "./gen/whatsapp/ws/v1/frames_pb.js";
