package auth

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/whatsapp-v2/server/internal/auth/domain"
	"github.com/whatsapp-v2/server/internal/platform/id"
	"github.com/whatsapp-v2/server/internal/platform/ratelimit"
)

// ─────────────────────────────── errors ─────────────────────────────────

// Error is a domain rejection with its wire mapping (api-standards §2).
type Error struct {
	Code       string
	Status     int
	Message    string
	Retryable  bool
	RetryAfter time.Duration
}

func (e *Error) Error() string { return e.Code + ": " + e.Message }

func rejection(status int, code, msg string) *Error {
	return &Error{Code: code, Status: status, Message: msg}
}

func transientErr() *Error {
	return &Error{Code: "TRANSIENT_UNAVAILABLE", Status: http.StatusServiceUnavailable,
		Message: "temporarily unavailable", Retryable: true}
}

// ErrNotFound is returned by repositories when no row matches.
var ErrNotFound = errors.New("auth: not found")

// ErrDeviceLimit is returned by the Registrar when the device cap is hit.
var ErrDeviceLimit = errors.New("auth: device limit reached")

// ─────────────────────────────── ports (implemented by adapters) ────────

// User is the slice of the users row auth needs.
type User struct {
	ID      string
	PINHash string // empty = no 2FA PIN set
	Status  int16  // 0 active | 1 suspended | 2 deleted
}

type ChallengeRepo interface {
	Create(ctx context.Context, ch domain.Challenge) error
	Get(ctx context.Context, id string) (domain.Challenge, error)
	IncrementAttempts(ctx context.Context, id string) error
	MarkVerified(ctx context.Context, id string, pinPending bool, at time.Time) error
}

type UserRepo interface {
	ByPhoneHash(ctx context.Context, phoneHash []byte) (User, error)
	ByID(ctx context.Context, id string) (User, error)
	SetPINHash(ctx context.Context, userID, phc string) error
}

type SessionRepo interface {
	ByRefreshHash(ctx context.Context, hash []byte) (domain.Session, error)
	ByRotatedFrom(ctx context.Context, hash []byte) (domain.Session, error)
	// Rotate swaps oldHash → newHash atomically; false = the old hash no
	// longer matched (a concurrent rotation won).
	Rotate(ctx context.Context, sessionID string, oldHash, newHash []byte, at time.Time) (bool, error)
	Revoke(ctx context.Context, sessionID string, at time.Time) error
}

// RegisterDeviceParams is the registration transaction input; IDs are
// pre-generated by the service so the adapter stays mechanical.
type RegisterDeviceParams struct {
	UserID           string // used only when the user is new
	PhoneHash        []byte
	DeviceID         string
	Platform         int16
	DeviceName       string
	IdentityKey      []byte
	SessionID        string
	RefreshHash      []byte
	SessionExpiresAt time.Time
	Now              time.Time
}

type RegisterDeviceResult struct {
	UserID  string
	NewUser bool
}

// Registrar performs user-if-new + device + session in ONE transaction.
type Registrar interface {
	RegisterDevice(ctx context.Context, p RegisterDeviceParams) (RegisterDeviceResult, error)
}

// Sender delivers OTP codes (adapters: mock/sms/email — HLD §17.5 swap point).
type Sender interface {
	Send(ctx context.Context, destination, code string) error
	Channel() domain.Channel
}

// Limiter matches ratelimit.ValkeyLimiter. Failing limiters fail CLOSED.
type Limiter interface {
	Allow(ctx context.Context, key string, p ratelimit.Params) (ratelimit.Result, error)
}

// AttemptLog feeds the abuse dashboard (otp_attempts table).
type AttemptLog interface {
	Record(ctx context.Context, phoneHash []byte, success bool, at time.Time) error
}

// ─────────────────────────────── service ────────────────────────────────

// Deps wires the service; every field is required.
type Deps struct {
	Challenges ChallengeRepo
	Users      UserRepo
	Sessions   SessionRepo
	Registrar  Registrar
	Sender     Sender
	Limiter    Limiter
	Attempts   AttemptLog
	Issuer     *TokenIssuer
	Log        *slog.Logger
}

// Service orchestrates the auth flows (FR-AUTH-01…08 subset for T0.08).
type Service struct {
	d          Deps
	pepper     []byte
	refreshTTL time.Duration
	now        func() time.Time
	entropy    io.Reader
}

// NewService builds the service. pepper keys phone-number HMACs; refreshTTL
// is the absolute session lifetime.
func NewService(d Deps, pepper string, refreshTTL time.Duration) *Service {
	return &Service{
		d:          d,
		pepper:     []byte(pepper),
		refreshTTL: refreshTTL,
		now:        time.Now,
		entropy:    rand.Reader,
	}
}

// Verify implements TokenVerifier (the context port).
func (s *Service) Verify(token string) (Identity, error) {
	return s.d.Issuer.Verify(token)
}

// PhoneHash is the peppered lookup hash for a handle (exported for the
// contacts context's hashed sync — same keying, single definition).
func (s *Service) PhoneHash(handle string) []byte {
	m := hmac.New(sha256.New, s.pepper)
	m.Write([]byte(strings.ToLower(strings.TrimSpace(handle))))
	return m.Sum(nil)
}

var (
	reE164  = regexp.MustCompile(`^\+[1-9][0-9]{6,14}$`)
	reEmail = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)
)

func (s *Service) validHandle(h string) bool {
	if s.d.Sender.Channel() == domain.ChannelEmail {
		return reEmail.MatchString(h)
	}
	// sms + mock take phone numbers.
	return reE164.MatchString(h)
}

// ─────────────────────────────── request-otp ────────────────────────────

type OTPRequest struct {
	Handle string // E.164 phone (or email in the email-OTP profile)
	IP     string
}

type OTPChallenge struct {
	ChallengeID string `json:"challenge_id"`
	Channel     string `json:"channel"`
}

// RequestOTP creates a challenge and sends the code. The response is
// IDENTICAL whether or not the handle belongs to an account (FR-AUTH-01,
// enumeration defense).
func (s *Service) RequestOTP(ctx context.Context, req OTPRequest) (OTPChallenge, error) {
	handle := strings.TrimSpace(req.Handle)
	if !s.validHandle(handle) {
		return OTPChallenge{}, rejection(http.StatusBadRequest, "VALIDATION_PHONE",
			"handle must be an E.164 phone number (or an email in the email-OTP profile)")
	}
	ph := s.PhoneHash(handle)

	// Abuse controls (api-standards §4): 3/hr + 5/day per number, 10/day per IP.
	limits := []struct {
		key string
		p   ratelimit.Params
	}{
		{fmt.Sprintf("rl:otp:num1h:%x", ph), ratelimit.Params{Rate: 3.0 / 3600, Burst: 3}},
		{fmt.Sprintf("rl:otp:num1d:%x", ph), ratelimit.Params{Rate: 5.0 / 86400, Burst: 5}},
		{"rl:otp:ip1d:" + req.IP, ratelimit.Params{Rate: 10.0 / 86400, Burst: 10}},
	}
	for _, l := range limits {
		res, err := s.d.Limiter.Allow(ctx, l.key, l.p)
		if err != nil {
			s.d.Log.Error("otp rate check unavailable — failing closed", "err", err)
			return OTPChallenge{}, transientErr()
		}
		if !res.Allowed {
			return OTPChallenge{}, &Error{Code: "RATE_LIMITED", Status: http.StatusTooManyRequests,
				Message: "too many OTP requests", Retryable: true, RetryAfter: res.RetryAfter}
		}
	}

	code, err := domain.NewCode(s.entropy)
	if err != nil {
		return OTPChallenge{}, transientErr()
	}
	salt := make([]byte, 16)
	if _, err := io.ReadFull(s.entropy, salt); err != nil {
		return OTPChallenge{}, transientErr()
	}
	now := s.now()
	ch := domain.Challenge{
		ID:        id.New(),
		PhoneHash: ph,
		CodeHash:  domain.HashCode(salt, code),
		Salt:      salt,
		Channel:   s.d.Sender.Channel(),
		CreatedAt: now,
		ExpiresAt: now.Add(domain.OTPValidity),
	}
	if err := s.d.Challenges.Create(ctx, ch); err != nil {
		s.d.Log.Error("otp challenge persist failed", "err", err)
		return OTPChallenge{}, transientErr()
	}
	if err := s.d.Sender.Send(ctx, handle, code); err != nil {
		s.d.Log.Error("otp send failed", "channel", ch.Channel.String(), "err", err)
		return OTPChallenge{}, transientErr()
	}
	return OTPChallenge{ChallengeID: ch.ID, Channel: ch.Channel.String()}, nil
}

// ─────────────────────────────── verify-otp ─────────────────────────────

type DeviceInfo struct {
	Platform    string // ios | android | web
	Name        string
	IdentityKey []byte // public Signal identity key
}

type TokenPair struct {
	AccessJWT    string `json:"access_jwt,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	UserID       string `json:"user_id,omitempty"`
	DeviceID     string `json:"device_id,omitempty"`
	SessionID    string `json:"-"`
	RequiresPIN  bool   `json:"requires_pin,omitempty"`
}

// VerifyOTP checks the code and either issues tokens, or — when the account
// has a 2FA PIN — returns RequiresPIN (SIM-swap defense, threat-model T4).
func (s *Service) VerifyOTP(ctx context.Context, challengeID, code string, dev DeviceInfo) (TokenPair, error) {
	ch, err := s.d.Challenges.Get(ctx, challengeID)
	if errors.Is(err, ErrNotFound) {
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_OTP_INVALID", "unknown challenge")
	}
	if err != nil {
		return TokenPair{}, transientErr()
	}
	now := s.now()

	switch domain.VerifyCode(ch, code, now) {
	case domain.VerifyOK:
		// fall through
	case domain.VerifyWrongCode:
		_ = s.d.Challenges.IncrementAttempts(ctx, ch.ID)
		_ = s.d.Attempts.Record(ctx, ch.PhoneHash, false, now)
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_OTP_INVALID", "wrong code")
	case domain.VerifyExpired:
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_OTP_EXPIRED", "challenge expired")
	case domain.VerifyTooManyAttempts:
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_OTP_INVALID", "attempts exhausted")
	case domain.VerifyAlreadyUsed:
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_OTP_INVALID", "challenge already used")
	}
	_ = s.d.Attempts.Record(ctx, ch.PhoneHash, true, now)

	u, err := s.d.Users.ByPhoneHash(ctx, ch.PhoneHash)
	switch {
	case err == nil && u.Status == 1:
		return TokenPair{}, rejection(http.StatusForbidden, "ACCOUNT_SUSPENDED", "account suspended")
	case err == nil && u.PINHash != "":
		// OTP passed but the PIN gate stands: mark and stop.
		if err := s.d.Challenges.MarkVerified(ctx, ch.ID, true, now); err != nil {
			return TokenPair{}, transientErr()
		}
		return TokenPair{RequiresPIN: true}, nil
	case err != nil && !errors.Is(err, ErrNotFound):
		return TokenPair{}, transientErr()
	}

	if err := s.d.Challenges.MarkVerified(ctx, ch.ID, false, now); err != nil {
		return TokenPair{}, transientErr()
	}
	return s.register(ctx, ch.PhoneHash, dev)
}

// VerifyPIN completes a pin-pending challenge (Argon2id check, hard limits).
func (s *Service) VerifyPIN(ctx context.Context, challengeID, pin string, dev DeviceInfo) (TokenPair, error) {
	ch, err := s.d.Challenges.Get(ctx, challengeID)
	if errors.Is(err, ErrNotFound) {
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_PIN_INVALID", "unknown challenge")
	}
	if err != nil {
		return TokenPair{}, transientErr()
	}
	now := s.now()
	if ch.VerifiedAt.IsZero() || !ch.PinPending {
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_PIN_INVALID", "challenge is not awaiting a pin")
	}
	if now.After(ch.ExpiresAt) {
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_OTP_EXPIRED", "challenge expired")
	}

	res, err := s.d.Limiter.Allow(ctx, fmt.Sprintf("rl:pin:%x", ch.PhoneHash),
		ratelimit.Params{Rate: 5.0 / 3600, Burst: 3})
	if err != nil {
		return TokenPair{}, transientErr()
	}
	if !res.Allowed {
		return TokenPair{}, &Error{Code: "RATE_LIMITED", Status: http.StatusTooManyRequests,
			Message: "too many pin attempts", Retryable: true, RetryAfter: res.RetryAfter}
	}

	u, err := s.d.Users.ByPhoneHash(ctx, ch.PhoneHash)
	if err != nil {
		return TokenPair{}, transientErr()
	}
	ok, err := domain.CheckPIN(u.PINHash, pin)
	if err != nil {
		s.d.Log.Error("stored pin hash unreadable", "user_id", u.ID, "err", err)
		return TokenPair{}, transientErr()
	}
	if !ok {
		_ = s.d.Attempts.Record(ctx, ch.PhoneHash, false, now)
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_PIN_INVALID", "wrong pin")
	}

	if err := s.d.Challenges.MarkVerified(ctx, ch.ID, false, now); err != nil { // consume
		return TokenPair{}, transientErr()
	}
	return s.register(ctx, ch.PhoneHash, dev)
}

func platformCode(p string) (int16, error) {
	switch p {
	case "ios":
		return 0, nil
	case "android":
		return 1, nil
	case "web":
		return 2, nil
	}
	return 0, fmt.Errorf("unknown platform %q", p)
}

func (s *Service) register(ctx context.Context, phoneHash []byte, dev DeviceInfo) (TokenPair, error) {
	platform, perr := platformCode(dev.Platform)
	if perr != nil || len(dev.IdentityKey) == 0 {
		return TokenPair{}, rejection(http.StatusBadRequest, "VALIDATION_DEVICE",
			"device platform (ios|android|web) and identity_key are required")
	}
	now := s.now()
	refresh, rhash, err := domain.NewRefreshToken(s.entropy)
	if err != nil {
		return TokenPair{}, transientErr()
	}
	p := RegisterDeviceParams{
		UserID:           id.New(),
		PhoneHash:        phoneHash,
		DeviceID:         id.New(),
		Platform:         platform,
		DeviceName:       dev.Name,
		IdentityKey:      dev.IdentityKey,
		SessionID:        id.New(),
		RefreshHash:      rhash,
		SessionExpiresAt: now.Add(s.refreshTTL),
		Now:              now,
	}
	res, err := s.d.Registrar.RegisterDevice(ctx, p)
	if errors.Is(err, ErrDeviceLimit) {
		return TokenPair{}, rejection(http.StatusForbidden, "STATE_DEVICE_LIMIT",
			"device limit reached (1 primary + 4 linked); revoke a device first")
	}
	if err != nil {
		s.d.Log.Error("device registration failed", "err", err)
		return TokenPair{}, transientErr()
	}
	access, err := s.d.Issuer.Issue(res.UserID, p.DeviceID, p.SessionID)
	if err != nil {
		s.d.Log.Error("token issue failed", "err", err)
		return TokenPair{}, transientErr()
	}
	return TokenPair{
		AccessJWT:    access,
		RefreshToken: refresh,
		UserID:       res.UserID,
		DeviceID:     p.DeviceID,
		SessionID:    p.SessionID,
	}, nil
}

// ─────────────────────────────── refresh / logout / pin ─────────────────

// Refresh rotates the refresh token. Replaying a superseded token is reuse:
// the whole session dies (FR-AUTH-04).
func (s *Service) Refresh(ctx context.Context, refreshToken string) (TokenPair, error) {
	h := domain.HashToken(refreshToken)
	now := s.now()

	sess, err := s.d.Sessions.ByRefreshHash(ctx, h)
	if errors.Is(err, ErrNotFound) {
		if old, err2 := s.d.Sessions.ByRotatedFrom(ctx, h); err2 == nil {
			_ = s.d.Sessions.Revoke(ctx, old.ID, now)
			s.d.Log.Warn("refresh token reuse detected — session revoked",
				"session_id", old.ID, "device_id", old.DeviceID)
			// TODO(T0.09): emit user.events so the user's other devices are alerted.
			return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_REFRESH_REUSED",
				"token reuse detected; session revoked")
		}
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_TOKEN_INVALID", "unknown refresh token")
	}
	if err != nil {
		return TokenPair{}, transientErr()
	}

	switch domain.EvaluateSession(sess, now) {
	case domain.RefreshRevoked:
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_DEVICE_REVOKED", "session revoked")
	case domain.RefreshExpired:
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_TOKEN_EXPIRED", "session expired; re-authenticate")
	case domain.RefreshRotate:
		// proceed
	}

	newTok, newHash, err := domain.NewRefreshToken(s.entropy)
	if err != nil {
		return TokenPair{}, transientErr()
	}
	ok, err := s.d.Sessions.Rotate(ctx, sess.ID, h, newHash, now)
	if err != nil {
		return TokenPair{}, transientErr()
	}
	if !ok {
		// A concurrent rotation won the race; this presentation is stale.
		return TokenPair{}, rejection(http.StatusUnauthorized, "AUTH_TOKEN_INVALID", "refresh conflict")
	}
	access, err := s.d.Issuer.Issue(sess.UserID, sess.DeviceID, sess.ID)
	if err != nil {
		return TokenPair{}, transientErr()
	}
	return TokenPair{
		AccessJWT:    access,
		RefreshToken: newTok,
		UserID:       sess.UserID,
		DeviceID:     sess.DeviceID,
		SessionID:    sess.ID,
	}, nil
}

// Logout revokes the caller's session (FR-AUTH-07).
func (s *Service) Logout(ctx context.Context, ident Identity) error {
	if err := s.d.Sessions.Revoke(ctx, ident.SessionID, s.now()); err != nil {
		return transientErr()
	}
	return nil
}

// SetPIN sets or changes the 2FA registration PIN (FR-AUTH-03).
func (s *Service) SetPIN(ctx context.Context, ident Identity, oldPIN, newPIN string) error {
	u, err := s.d.Users.ByID(ctx, ident.UserID)
	if err != nil {
		return transientErr()
	}
	if u.PINHash != "" {
		ok, err := domain.CheckPIN(u.PINHash, oldPIN)
		if err != nil || !ok {
			return rejection(http.StatusUnauthorized, "AUTH_PIN_INVALID", "current pin is wrong")
		}
	}
	phc, err := domain.HashPIN(newPIN, s.entropy)
	if err != nil {
		return rejection(http.StatusBadRequest, "VALIDATION_PIN", err.Error())
	}
	if err := s.d.Users.SetPINHash(ctx, ident.UserID, phc); err != nil {
		return transientErr()
	}
	return nil
}
